import Head from "next/head";
import Image from "next/image";
import {
  Product,
  Navbar,
  Footer,
  FooterBanner,
  Layout,
  Banner,
  Cart,
} from "../components";
import { client } from "../lib/client";
import styles from "../styles/Home.module.css";

// eslint-disable-next-line @next/next/no-typos
export const getServerSideProps = async () => {
  const query = `*[_type == "product"]`;
  const products = await client.fetch(query);
  const bannerQuery = `*[_type == "banner"]`;
  const banner = await client.fetch(bannerQuery);

  return {
    props: {
      products,
      banner,
    },
  };
};

export default function Home({ products, banner }) {
  console.log(banner, products);
  return (
    <div className={styles.container}>
      <Head>
        <title>E-commerce App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Navbar /> */}
        <Banner banner={banner.length && banner[0]} />
        <div className={styles.product__wrapper}>
          {products?.map((product) => (
            <Product key={product._id} product={product} />
          ))}
        </div>
        <Cart />
        <Footer />
      </main>
    </div>
  );
}
